import type { Job } from "./types";

export const defaultJobs: Job[] = [
  {
    id: "1",
    title: "Senior Backend Engineer",
    team: "Engineering",
    location: "Lagos, Nigeria",
    type: "Full-time",
    level: "Senior",
    description:
      "We are looking for a Senior Backend Engineer to help build and scale our content fingerprinting and piracy detection infrastructure. You will design and implement high-throughput APIs and data pipelines that power our platform.",
    requirements: [
      "5+ years of backend development experience",
      "Proficiency in Node.js/TypeScript or Python",
      "Experience with distributed systems and microservices",
      "Strong understanding of databases (SQL & NoSQL)",
      "Experience with cloud platforms (AWS/GCP)",
    ],
    responsibilities: [
      "Design and implement scalable APIs and services",
      "Build and maintain data pipelines for content fingerprinting",
      "Collaborate with product and data teams on new features",
      "Mentor junior engineers and review code",
      "Participate in on-call rotations",
    ],
    createdAt: "2026-02-10T00:00:00.000Z",
    isActive: true,
  },
  {
    id: "2",
    title: "Frontend Engineer",
    team: "Engineering",
    location: "Remote, Africa",
    type: "Full-time",
    level: "Mid-level",
    description:
      "Join our frontend team to build beautiful, performant user interfaces for our dashboard and content protection tools. You will work closely with designers and product managers to ship delightful experiences.",
    requirements: [
      "3+ years of frontend development experience",
      "Strong proficiency in React and TypeScript",
      "Experience with Next.js or similar frameworks",
      "Understanding of web performance and accessibility",
      "Eye for design and attention to detail",
    ],
    responsibilities: [
      "Develop and maintain the FairPlay dashboard",
      "Build reusable UI components and design systems",
      "Optimize application performance and accessibility",
      "Work closely with designers to implement pixel-perfect UIs",
      "Write comprehensive tests for frontend components",
    ],
    createdAt: "2026-02-08T00:00:00.000Z",
    isActive: true,
  },
  {
    id: "3",
    title: "Data Scientist",
    team: "Data Science",
    location: "Remote, Global",
    type: "Full-time",
    level: "Mid-level",
    description:
      "We need a Data Scientist to develop and improve our piracy detection algorithms. You will work with large datasets of audio/video fingerprints and help us stay ahead of content pirates across the continent.",
    requirements: [
      "3+ years of experience in data science or ML engineering",
      "Strong Python skills with experience in ML frameworks",
      "Experience with audio/video processing is a plus",
      "Solid understanding of statistics and ML fundamentals",
      "Experience with big data tools (Spark, etc.)",
    ],
    responsibilities: [
      "Develop and improve content matching algorithms",
      "Build ML models for piracy detection and prediction",
      "Analyze patterns in piracy data across African markets",
      "Collaborate with engineering to deploy models to production",
      "Present findings to stakeholders and leadership",
    ],
    createdAt: "2026-02-05T00:00:00.000Z",
    isActive: true,
  },
  {
    id: "4",
    title: "Product Designer",
    team: "Design",
    location: "Lagos, Nigeria",
    type: "Full-time",
    level: "Mid-level",
    description:
      "We are looking for a Product Designer to shape the user experience of our platform. You will design intuitive workflows for filmmakers and content creators to protect and monetize their work.",
    requirements: [
      "3+ years of product design experience",
      "Strong portfolio demonstrating UX/UI skills",
      "Proficiency in Figma or similar design tools",
      "Experience with design systems",
      "Understanding of user research methodologies",
    ],
    responsibilities: [
      "Design end-to-end user flows for the FairPlay platform",
      "Conduct user research and usability testing",
      "Maintain and evolve the design system",
      "Collaborate with engineers to ship high-quality products",
      "Create prototypes for new product concepts",
    ],
    createdAt: "2026-02-01T00:00:00.000Z",
    isActive: true,
  },
  {
    id: "5",
    title: "Business Development Manager",
    team: "Marketing & Sales",
    location: "Nairobi, Kenya",
    type: "Full-time",
    level: "Senior",
    description:
      "Drive partnerships and market expansion across East Africa. You will build relationships with studios, distributors, and streaming platforms to grow FairPlay's presence in the region.",
    requirements: [
      "5+ years of business development experience",
      "Deep knowledge of the African media & entertainment industry",
      "Strong network in the East African entertainment sector",
      "Excellent communication and presentation skills",
      "Experience with B2B sales cycles",
    ],
    responsibilities: [
      "Identify and close partnership deals across East Africa",
      "Build and manage relationships with key stakeholders",
      "Develop go-to-market strategies for new regions",
      "Represent FairPlay at industry events and conferences",
      "Collaborate with product team on market-specific needs",
    ],
    createdAt: "2026-01-28T00:00:00.000Z",
    isActive: true,
  },
  {
    id: "6",
    title: "Legal & Compliance Analyst",
    team: "Legal & Compliance",
    location: "Accra, Ghana",
    type: "Full-time",
    level: "Mid-level",
    description:
      "Support our legal and compliance operations across multiple African jurisdictions. You will help navigate copyright law, data protection regulations, and content licensing frameworks.",
    requirements: [
      "Law degree or equivalent qualification",
      "2+ years of experience in IP law, media law, or compliance",
      "Familiarity with copyright laws across African countries",
      "Understanding of data protection regulations (GDPR, POPIA, etc.)",
      "Excellent analytical and writing skills",
    ],
    responsibilities: [
      "Review and draft partnership and licensing agreements",
      "Monitor regulatory developments across African markets",
      "Advise product teams on legal and compliance requirements",
      "Support takedown processes and enforcement actions",
      "Develop compliance training materials for the team",
    ],
    createdAt: "2026-01-25T00:00:00.000Z",
    isActive: true,
  },
  {
    id: "7",
    title: "DevOps Engineer",
    team: "Engineering",
    location: "Remote, Africa",
    type: "Full-time",
    level: "Senior",
    description:
      "Build and maintain the infrastructure that powers FairPlay's platform. You will work on CI/CD pipelines, container orchestration, monitoring, and security to ensure high availability and reliability.",
    requirements: [
      "5+ years of DevOps or SRE experience",
      "Strong experience with Kubernetes and Docker",
      "Proficiency with cloud platforms (AWS/GCP/Azure)",
      "Experience with IaC tools (Terraform, Pulumi)",
      "Strong understanding of security best practices",
    ],
    responsibilities: [
      "Design and manage cloud infrastructure",
      "Build and maintain CI/CD pipelines",
      "Implement monitoring, alerting, and incident response",
      "Optimize infrastructure costs and performance",
      "Ensure security and compliance of all systems",
    ],
    createdAt: "2026-01-20T00:00:00.000Z",
    isActive: true,
  },
];
